version: '3.7'
services:
  chabok-service:
    build:
      context: ./backend/
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
networks:
  chabok:
    driver: bridge    